---

- name: Copy file from local to remote clients
  hosts: all

  tasks:
    - name: Copying file
      become: true
      copy:
                         src: /home/ch/some.cfg
                         dest: /tmp
                         owner: test
                         mode: 0644 
