---
- name: Create users thru loop
  hosts: all
  vars:
    users: [jerry,kramer,eliane]

     
    tasks: 
    - name: Create users
      users: 
         name: '{{item}}'
      with_items: '{{users}}' 
